### ISSUE TITLE
The AndroidManifest.xml is super broken

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#1]
I have no idea what's going on, but half the Activities in the AndroidManifest.xml are complaining. This needs investigation. It seems like every activity other than Main crashed when launched because it's not defined in the manifest.

**Comment by ounsworth** [comment]
Actually, many things are broken. I need to carefully re-merge The-Blue-Alliance with MCMergeManager/master.

**Comment by georgetzavelas** [comment]
Are you sure they are broken or maybe you are missing something from your SDK install?  I know it took a few tries for me to get mine working and I had to consult with Connor to do it properly.

**Comment by ounsworth** [comment]
Everything has been corrected from the mega merge of porting The-Blue-Alliance from Knigdt Watch.
