### ISSUE TITLE
Judge Binder: data flow diagram

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#102]
![img_20170211_151810](https://cloud.githubusercontent.com/assets/5394395/22857174/2ed4fb6e-f06e-11e6-8c62-5dfbf8443e07.jpg)

**Comment by ounsworth** [comment]
I've started an infographic for this:

https://magic.piktochart.com/infographic/saved/20371756

**Comment by ounsworth** [comment]
@Zinka010 @GabbyGenereux This has been done, right? We can close this ticket?

**Comment by Zinka010** [comment]
It has been done.
