### ISSUE TITLE
Make files viewable from PC

### ISSUE THREAD

**Issue by atoms118** [FRC2706/MCMergeManager#105]
- [x] Photos taken by the app
- [x] .json data files

**Comment by ounsworth** [comment]
WOW! The problem is that files only show up over USB once they have been "media scanned", which usually only happens on phone boot.

This line of code will force it to scan a given file:

    App.getContext().sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(file)));
