### ISSUE TITLE
Team schedule, team number prompt

### ISSUE THREAD

**Issue by georgetzavelas** [FRC2706/MCMergeManager#13]
When entering the team number, alpha characters are permitted.  It would be nice to limit the input to only numbers.

**Comment by ounsworth** [comment]
I agree, but I'm not sure how to do that since Connor set that up with some kind of System dialog, so I don't have direct access to the text box.

@Stealth2994 I think you said you had solved that?

**Comment by ounsworth** [comment]
Connor told me where to find that, done.
