### ISSUE TITLE
Gears dropped not going through to TeamStatsReport

### ISSUE THREAD

**Issue by atoms118** [FRC2706/MCMergeManager#146]
Most likely an issue with the StatsEngine

**Comment by ounsworth** [comment]
So, I've thought about this, and I think the correct behaviour is to record a gear Fail, and have the stat `teleop_gearsDropped_avgPerMatch` not be zero, but not to count a drop as the end of a cycle. My logic is this: imagine a team that has a lot of troubles picking up / holding a gear, they might have data like this:

time=12s, gear pickup
time=17s, gear drop
time=21s, gear pickup
time=25s, gear drop
time=30s, gear pickup
time=60s, gear score

If I counted a drop as the end of a cycle, we'd get average cycle time of 13s (or 30s if we only count the success). I think the right thing is to count the whole thing as a single cycle 48 seconds long.

(So the only way to fail a cycle is to hit the end of the match)

I'll go through the code to make sure it's doing this.

@Zinka010

**Comment by ounsworth** [comment]
Closed by commit 0b4aa9b
