### ISSUE TITLE
Picture resolution

### ISSUE THREAD

**Issue by Zinka010** [FRC2706/MCMergeManager#157]
Pictures can be no more than 4096x4096.

**Comment by ounsworth** [comment]
@wall-daniel I think you've done this, right? Can we close this ticket?

**Comment by wall-daniel** [comment]
I have done this, but i have only tested this on my phone. Also the pictures on the server need to be changed.

**Comment by ounsworth** [comment]
@wall-daniel Ok cool. It looks like I have some free time this afternoon, so I can test it on my phone, and update the photos on the FTP server.

It doesn't look like your changes from last saturday are on Master, can you point me to the branch / commit with the picture sizing changes?

**Comment by wall-daniel** [comment]
@ounsworth I created a pull request where you can see the changes. Also in the pull request is changing the file syncing and loading to onResume().

**Comment by ounsworth** [comment]
@wall-daniel Ah, it's on a branch called `DanielWall_#76_JSON`. That explains why nothing jumped out at me when I looked at the open branches.

K, I'll put this on my phone and update the photos on the server now. That PR is approved, so feel free to merge it whenever.

**Comment by ounsworth** [comment]
AWW YEAH! As soon as I updated the app, it went to town downsizing my images (see all those "foto too large"s?):

The `MCMergeManeger/Team Photos` directory went from 139 mb --> 26 mb. You rock! I'll wipe what's on the FTP server and upload these instead. 

![screenshot from 2017-03-22 17-14-27](https://cloud.githubusercontent.com/assets/5394395/24221048/26affa82-0f23-11e7-9f22-1cec389eb06a.png)

**Comment by ounsworth** [comment]
I'm re-opening so I can investigate why images are getting mangled, like this:

![1114_1489187275606](https://cloud.githubusercontent.com/assets/5394395/24248030/2a331d5c-0fa4-11e7-95b2-6d39a1a0205e.jpg)

**Comment by ounsworth** [comment]
I think I've found the bug:

```java
options.inSampleSize = inSampleSize;
...
              
// tries to save the image that is downsized
try {
      Bitmap b= BitmapFactory.decodeFile(subFile.getAbsolutePath(), options);
      Bitmap out = Bitmap.createScaledBitmap(b, b.getWidth(), b.getHeight(), false);
     ...
```

From the docs:

"If set to a value > 1, requests the decoder to subsample the original image, returning a smaller image to save memory."

"subsample = 4" means that rather than scale properly, it only loads every 4th pixel (ie the image is 3/4 empty pixels or something). This is a quick&dirty way showing a smaller image on the screen without needing to do a lot of processing. But in the next line we take this cheaply subsampled (3/4 empty) image and hand it to the function to downsample properly.

**Comment by ounsworth** [comment]
I replaced with this, is seems to be behaving better. I'll run all 250mb of photos through it and make sure that none get corrupted. I'll report back.

```java
Bitmap fullImg = BitmapFactory.decodeFile(subFile.getAbsolutePath(), options);
Bitmap out = Bitmap.createScaledBitmap(fullImg, fullImg.getWidth() / inSampleSize,
                                    fullImg.getHeight() / inSampleSize, false);
```

**Comment by ounsworth** [comment]
Crap, images are still getting corrupted. Looks like I'm not done.

**Comment by wall-daniel** [comment]
Can this ticket be closed? @ounsworth

**Comment by ounsworth** [comment]
@wall-daniel umm, yup, looks that way :)
