### ISSUE TITLE
Stats for how many matches a team was dead for

### ISSUE THREAD

**Issue by TMSD** [FRC2706/MCMergeManager#168]

**Comment by ounsworth** [comment]
@TMSD Will this do?

![screenshot_20170328-213223](https://cloud.githubusercontent.com/assets/5394395/24434980/a798c98a-1400-11e7-8e94-88a9f535342d.png)

**Comment by TMSD** [comment]
I did not submit that, however I think danny did. He was using my laptop
when he submited that I think. But in my opinion its good.

-Ethan

**Comment by ounsworth** [comment]
Ah, thanks. @wall-daniel will this do?

**Comment by ounsworth** [comment]
Done and merged to master.
