### ISSUE TITLE
Put attribution and OSS licence blurb into readme.md

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#177]
See the discussion on this wiki page:
https://github.com/FRC2706/2018-2706-Robot-Code/wiki/Draft-attribution-blurb-for-2706-code

**Comment by Zinka010** [comment]
I can add this right now if no one has any complaints(Just copying what Kevin wrote).

**Comment by ounsworth** [comment]
Let me do 10 mins of googling and stick a legally-binding license in there.

**Comment by ounsworth** [comment]
Ok, I updated the wiki page with license stuff.

Let's start a discussion on Discord to see if anyone objects, give it 24 hours for people to reply, then you can go ahead and add this to the repo.

**Comment by Zinka010** [comment]
Ok
