### ISSUE TITLE
What is com.google.gson?

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#2]
When I download master, the file TeamInfoFragment.java has errors on the following lines about not being able to find com.google.gson:

26  import com.google.gson.JsonElement;
27  import com.google.gson.JsonObject;
28  import com.google.gson.JsonParser;

A quick google shows that gson is a jar that needs to be downloaded. Did you have to download something to get this working? If so, it needs to be checked in to git.

The build.gradle has this rule:
  compile fileTree(include: ['*.jar'], dir: 'libs')
so presumably if I dropped the gson jar in, it would work, but since I didn't cause this problem, I shouldn't be the one to fix it.

**Comment by georgetzavelas** [comment]
This library is already in master

**Comment by ounsworth** [comment]
Scouting/libs/gson-2.2.2.jar

So it is. Some massaging of gradle files needed?

**Comment by georgetzavelas** [comment]
Apparently you right click on the library and say "add as library".  I did that and updated the project. Do a pull and you should have it.

**Comment by ounsworth** [comment]
I am in the middle of deep surgery. Will that pull make me unhappy?

**Comment by georgetzavelas** [comment]
Do your surgery for now and I will be there in just over an hour and we can work through it.

**Comment by ounsworth** [comment]
Cool. Sounds like it's an easy change to replicate. 

No rush on getting here, I'll be entertained for a while yet. -_-
