### ISSUE TITLE
What happens if we delete the file thebluealliance.json?

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#3]
Based on the following commented out line in `FileUtils.java`:

    // if (! file exitst(/MCMergeManager/<TeamName>/<EventName>/thebluealliance.json) )

what happens if we use a file browser to delete the file `thebluealliance.json`, then do an online / offline search? Will the app crash with fireworks??

**Comment by Stealth2994** [comment]
No, it checks 1. if the file exists 2. if the team exists and then it gives the data back

**Comment by ounsworth** [comment]
You'll have to show me where in the code that check is to see if the file exists, cause I'm not seeing it.

Either way, deleting a file is a good test to do.
