### ISSUE TITLE
[XML] Capture how much time teams spend repairing

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#46]
If teams are constantly doing major repairs to their robot, this indicates that they will not be reliable during eliminations. Also, if they are doing major repairs right before alliance selection, this should be a red flag.

We should think of an app page to capture this page as someone walks through the pits, and think about how to use it in the statistics.

**Comment by wall-daniel** [comment]
I can probably do this over the Christmas break. Does putting the button on the home page, next to the 'take a picture' button sound good?

**Comment by atoms118** [comment]
Basically done, just waiting for pull to be approved

**Comment by ounsworth** [comment]
Approved!

Go ahead and merge.


-Mike

**Comment by ounsworth** [comment]
@atoms118 I'm gonna re-open this and ask that you use a grid layout or something so there's better horizontal spacing (would help with fat-fingering)

**Comment by atoms118** [comment]
Added spaces. Haven't sent a pull yet though, because I'm doing other stuff on that branch
