### ISSUE TITLE
Team Info Update

### ISSUE THREAD

**Issue by Underscorpion** [FRC2706/MCMergeManager#47]
I think what could be semi useful and semi for show would be to update the team info page a little bit. For example if I searched up "1114" in the team info, it would maybe have a picture of their team and/or logo. Also perhaps have their nickname would be set to "Simbotics" . And maybe even some little achievement icons that appear under their nickname that symbolize things such as" world champion winner" or something. 

However this stuff might be a bit unnecessary and not as important as some of the other problems, but if we ever get everything done we could work on it, or maybe we could work on it when we aren't in build season.

**Comment by ounsworth** [comment]
Good thought Matthew.

Things like nickname to "Simbotics" already is there, you just have to wait a second or two for the internet data to load.

I think what you're asking for here is closely related to #45 ; pictures, logos, achievements would be awesome to display, but where are we getting that data from? TheBlueAlliance has some of this, so let's do some poking to see what's available to be grabbed by the app.

**Comment by ounsworth** [comment]
Closing this issue because Matthew is no longer on the Android team, and Justin is working on this under another ticket.
