### ISSUE TITLE
We need a way to sync data between stands and drive team

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#48]
Some sort of web server to sync data to (database or ftp or something).

This is going to be a big project, much learning!

There are 3 data transfer problems we need to tackle:

1. Transferring match data between scouts' phones with no wifi.
2. Transferring match data from the scouts in the stands to the drive team (internet can be used here). Probably an SQL server with George's help is the right solution for this.
3. Saving and synching photos of other teams that our scouts have taken in the pits. This can be a one-time thing once we are back at the hotel. Nathan wants to use an FTP server for this.

**Comment by ounsworth** [comment]
Kevin gave the great idea of using QR codes, see ticket #52. That would solve problem 1 of getting data between phones with no internet, but it does not help with 2 or 3, we still need a database and FTP server.

**Comment by georgetzavelas** [comment]
RoR server is up and running in AWS, please raise any issues for bugs found
![yes](https://cloud.githubusercontent.com/assets/3611823/22621546/2e2024de-eaf4-11e6-9327-2a88e052f038.jpg)
