### ISSUE TITLE
Steamworks: [Java] Update data objects

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#56]

**Comment by wall-daniel** [comment]
# Notes:

What new data objects needed:
- FuelPickup
- FuelShoot
- Gear pickup
- Gear dropoff
- 

Stuff that need to be updated:
- AutoScoutingObject
- TeleopObject
- Scaling object
- PreGameObject
- postgameobject
- matchdata
- ?matchSchedule?

**Comment by ounsworth** [comment]
I made them into check boxes, because everybody loves checking off check boxes!

Match schedule probably doesn't need updating, I imagine it would stay the same from year to year.

**Comment by wall-daniel** [comment]
TODO: test matchdata to make sure the stuff is going to be saved/parsed properly
