### ISSUE TITLE
Steamworks: pre-match strategy pane & team summary

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#58]
What info does the drive team want pre-match?

- [ ] Team summary page (Gabby's comment below)
- [x] remove defenses stuff
- [x] Pre-Match Report (Mike's comment below)

**Comment by ounsworth** [comment]
@GabbyGenereux What data would you like in the "Summary" group on this page?

![screenshot_20170219-165654](https://cloud.githubusercontent.com/assets/5394395/23107099/e3380acc-f6c4-11e6-8e5a-4228b09c1223.png)

**Comment by GabbyGenereux** [comment]
Here's what I think would be valuable to have in the summary:

- Something that says whether they favor gears or balls during teleop
- Where they favourably obtain their gears/balls (wall, ground, hopper, etc)
- How long it takes them to get from pickup to scoring (I assume of their favourable game piece, but it could be a mix of both if that's easier) (basically I just want to know if we're on an alliance with them how long I should expect them to take to score something) (I wouldn't be upset if this doesn't make it on the summary list)
- Their favourable scoring position (for gears) or/and high/low goal (for fuel) (this one is the one I'm the least interested out of the list, also wouldn't be upset if it didn't make it on the summary list)

**Comment by ounsworth** [comment]
Also, it would be cool if we added this to the Pre-Match Report (below the predicted score). It should be just adding up averages.

> Blue expected: X Gears
>                          Y Fuel
>                          Z Climbs
> 
> Red expected:  X Gears
>                          Y Fuel
>                           Z Climbs

![screenshot_20170220-085102](https://cloud.githubusercontent.com/assets/5394395/23127715/077049d8-f74a-11e6-88d7-aecd5824844d.png)
