### ISSUE TITLE
Pit scouting page

### ISSUE THREAD

**Issue by cheeseburgur101** [FRC2706/MCMergeManager#59]
What their robot is able to do, how it looks (not fashion wise) etc...

**Comment by ounsworth** [comment]
Remember that people will exaggerate ("oh yeah, we can totally do 6 Gears per match!").

So you want to keep pit scouting questions purely fact-based that leave no room for exaggeration (ex.: "Do you have a climbing mechanism?", "What are your wheels made out of?", etc).

**Comment by cheeseburgur101** [comment]
^ plussing on that, if they exaggerate we should also write that down because it says something about their team!

**Comment by cheeseburgur101** [comment]
A starter list for things we we should record in the pit is:

1.  If their robot picks up fuel, how does it pick them up (off the ground, from a hopper)
2.  If their robot picks up gears, how does it pick them up( of the ground, from a Human Player)
3.  Is their robot able to climb?
4.  if their robot does fuel, what's the average amount they can carry in their robot at a time
5.  Does the robot look well built? (we don't want it breaking during a match!)
6.  Does their team look like people we want to play with us? (are they aggressive, annoying, etc)
7.  What their drive train is (tank or some other special one (the one that moves sideways))
8.  what wheels they use
9.  If they can climb, how do they climb
10. Does their robot resemble the robot kit that FIRST sent out?

With most of these you won't get a 'oh we can do x many gears' but even this may be useful because if their team is lying or exaggerating, we may not want them on our alliance.

**Comment by ounsworth** [comment]
I wouldn't judge a team too harshly if they exaggerate / lie because often the veterans are busy working on the robot and you end up talking to a grade 8 rookie who doesn't know the answer, so they make up something to not look dump. That happens a lot and isn't really a reflection of the team as a whole.

Better is to design the questions so that even a clueless grade 8 can answer them properly :)
