### ISSUE TITLE
Team Stats Page needs more data

### ISSUE THREAD

**Issue by atoms118** [FRC2706/MCMergeManager#75]
**Additional Data Needed For Team Stats Page:**

- [ ] Total missed ball pickups in teleop
- [x] Total number of low shots all-time (Not averaged; all matches)
- [x] Total number of high shots all-time (Not averaged; all matches)

**Comment by ounsworth** [comment]
Missed fuel pickups I can't give you based on the way the data works right now.
@wall-daniel @Zinka010 Do you think it would be easy to record missed / failed fuel pickups?

@atoms118 I added the following two stats for you:

```java
teamStatsReport.teleop_fuelScoredHigh_total;
teamStatsReport.teleop_fuelScoredLow_total;
```

You'll have to review merge my pull request #77.
