### ISSUE TITLE
Convert data objects to json and push / pull from db server

### ISSUE THREAD

**Issue by wall-daniel** [FRC2706/MCMergeManager#76]
Class that converts stuff to json so that it can work with the server

**Comment by georgetzavelas** [comment]
As discussed with Danny, he can see the JSON format by going to http://ftp.team2706.ca:3000/apidocs/

**Comment by ounsworth** [comment]
Danny, once Nathan is done updating the Settings page #86, you should replace hard-coded strings of "http://ftp.team2706.ca:300/..." with the URL that the user types into the settings page.

**Comment by ounsworth** [comment]
As part of this ticket I'm gonna work on saving / loading these objects from a file on the phone.

**Comment by wall-daniel** [comment]
TODO:

[ ] - Convert data objects to json
[ ] - save dataobjects as json to file
[ ] - load json stuff from file

**Comment by ounsworth** [comment]
@wall-daniel This has been done, right? We can close this ticket?
