### ISSUE TITLE
Repair Time: connect to data object and save to file

### ISSUE THREAD

**Issue by ounsworth** [FRC2706/MCMergeManager#94]
When the SUBMIT button is pressed, the data should be put into a bunch of `backend.dataObjects.RepairTimeObject`s and handed to `FileUtils.appendToTeamDataFile(TeamDataObject teamDataObject)` to be saved to a file.

- [x] Create RepairTimeObjects
- [ ] Submit RepairTimeObjects to...?

**Comment by atoms118** [comment]
Going to continue using atoms118_repair_UI for this. Need to fix Gradle first though (Mysteriously stopped working D:)

**Comment by ounsworth** [comment]
Yeah, I was fighting with that for an hour today too :(

I think Justin upgraded Gradle on his laptop and checked that in to
steamwork_integration. Now it's filtering through the branches.

I think it went away when I went Settings > Build, Execution, Deployment >
Gradle and selected "Use default gradle wrapper (recommended)".



On 9 Feb 2017 7:52 pm, "Alden Peeters" <notifications@github.com> wrote:

Going to continue using atoms118_repair_UI for this. Need to fix Gradle
first though (Mysteriously stopped working D:)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FRC2706/MCMergeManager/issues/94#issuecomment-278825321>,
or mute the thread
